// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLKS_WebMVC.Data;

#nullable disable

namespace QLKS_WebMVC.Migrations
{
    [DbContext(typeof(QLKS_WebMVCContext))]
    partial class QLKS_WebMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLKS_WebMVC.Models.DatPhong", b =>
                {
                    b.Property<int>("MaDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDat"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDat");

                    b.HasIndex("MaKH");

                    b.ToTable("DatPhong");

                    b.HasData(
                        new
                        {
                            MaDat = 1,
                            MaKH = 1,
                            MaPhong = 1,
                            NgayDat = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayNhan = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTra = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QLKS_WebMVC.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            CCCD = "12345",
                            DiaChi = "Nam Dinh",
                            HoTen = "Do Hoang Minh",
                            SDT = "123456789"
                        });
                });

            modelBuilder.Entity("QLKS_WebMVC.Models.DatPhong", b =>
                {
                    b.HasOne("QLKS_WebMVC.Models.KhachHang", "KhachHang")
                        .WithMany("DanhSachDatPhong")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QLKS_WebMVC.Models.KhachHang", b =>
                {
                    b.Navigation("DanhSachDatPhong");
                });
#pragma warning restore 612, 618
        }
    }
}
